// Generated by CoffeeScript 1.3.1
(function() {
  var PianoKey, PianoKeyboard, PianoKeyboardDesign,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PianoKeyboardDesign = (function() {

    PianoKeyboardDesign.name = 'PianoKeyboardDesign';

    PianoKeyboardDesign.prototype.KeyType = {
      WhiteC: 0,
      WhiteD: 1,
      WhiteE: 2,
      WhiteF: 3,
      WhiteG: 4,
      WhiteA: 5,
      WhiteB: 6,
      Black: 7
    };

    PianoKeyboardDesign.prototype.whiteKeyStep = 0.236;

    PianoKeyboardDesign.prototype.whiteKeyWidth = 0.226;

    PianoKeyboardDesign.prototype.whiteKeyHeight = 0.22;

    PianoKeyboardDesign.prototype.whiteKeyLength = 1.50;

    PianoKeyboardDesign.prototype.blackKeyWidth = 0.10;

    PianoKeyboardDesign.prototype.blackKeyHeight = 0.32;

    PianoKeyboardDesign.prototype.blackKeyLength = 1.00;

    PianoKeyboardDesign.prototype.blackKeyShiftCDE = 0.0216;

    PianoKeyboardDesign.prototype.blackKeyShiftFGAB = 0.0340;

    PianoKeyboardDesign.prototype.noteDropPosZ4WhiteKey = 0.25;

    PianoKeyboardDesign.prototype.noteDropPosZ4BlackKey = 0.75;

    PianoKeyboardDesign.prototype.whiteKeyColor = 0xffffff;

    PianoKeyboardDesign.prototype.blackKeyColor = 0x111111;

    PianoKeyboardDesign.prototype.keyDip = 0.07;

    PianoKeyboardDesign.prototype.keyUpSpeed = 0.03;

    PianoKeyboardDesign.prototype.keyInfo = [];

    function PianoKeyboardDesign() {
      var i, _i;
      for (i = _i = 0; _i < 128; i = ++_i) {
        this.keyInfo[i] = {};
      }
      this._initKeyType();
      this._initKeyPos();
    }

    PianoKeyboardDesign.prototype._initKeyType = function() {
      var Black, KeyType, WhiteA, WhiteB, WhiteC, WhiteD, WhiteE, WhiteF, WhiteG, i, keyInfo, noteNo, _i;
      keyInfo = this.keyInfo, KeyType = this.KeyType;
      WhiteC = KeyType.WhiteC, WhiteD = KeyType.WhiteD, WhiteE = KeyType.WhiteE, WhiteF = KeyType.WhiteF, WhiteG = KeyType.WhiteG, WhiteA = KeyType.WhiteA, WhiteB = KeyType.WhiteB, Black = KeyType.Black;
      for (i = _i = 0; _i < 10; i = ++_i) {
        noteNo = i * 12;
        keyInfo[noteNo + 0].keyType = WhiteC;
        keyInfo[noteNo + 1].keyType = Black;
        keyInfo[noteNo + 2].keyType = WhiteD;
        keyInfo[noteNo + 3].keyType = Black;
        keyInfo[noteNo + 4].keyType = WhiteE;
        keyInfo[noteNo + 5].keyType = WhiteF;
        keyInfo[noteNo + 6].keyType = Black;
        keyInfo[noteNo + 7].keyType = WhiteG;
        keyInfo[noteNo + 8].keyType = Black;
        keyInfo[noteNo + 9].keyType = WhiteA;
        keyInfo[noteNo + 10].keyType = Black;
        keyInfo[noteNo + 11].keyType = WhiteB;
      }
      noteNo = 120;
      keyInfo[noteNo + 0].keyType = WhiteC;
      keyInfo[noteNo + 1].keyType = Black;
      keyInfo[noteNo + 2].keyType = WhiteD;
      keyInfo[noteNo + 3].keyType = Black;
      keyInfo[noteNo + 4].keyType = WhiteE;
      keyInfo[noteNo + 5].keyType = WhiteF;
      keyInfo[noteNo + 6].keyType = Black;
      return keyInfo[noteNo + 7].keyType = WhiteB;
    };

    PianoKeyboardDesign.prototype._initKeyPos = function() {
      var Black, KeyType, WhiteA, WhiteB, WhiteC, WhiteD, WhiteE, WhiteF, WhiteG, blackKeyShiftCDE, blackKeyShiftFGAB, keyInfo, noteNo, posX, prevKeyType, shift, whiteKeyStep, _i, _j, _results;
      KeyType = this.KeyType, keyInfo = this.keyInfo, whiteKeyStep = this.whiteKeyStep, blackKeyShiftCDE = this.blackKeyShiftCDE, blackKeyShiftFGAB = this.blackKeyShiftFGAB;
      WhiteC = KeyType.WhiteC, WhiteD = KeyType.WhiteD, WhiteE = KeyType.WhiteE, WhiteF = KeyType.WhiteF, WhiteG = KeyType.WhiteG, WhiteA = KeyType.WhiteA, WhiteB = KeyType.WhiteB, Black = KeyType.Black;
      noteNo = 0;
      prevKeyType = WhiteB;
      posX = 0.0;
      shift = 0.0;
      keyInfo[noteNo].keyCenterPosX = posX;
      prevKeyType = keyInfo[noteNo].keyType;
      for (noteNo = _i = 1; _i < 128; noteNo = ++_i) {
        if (prevKeyType === Black) {
          if (keyInfo[noteNo].keyType === Black) {

          } else {
            posX += whiteKeyStep / 2.0;
          }
        } else {
          if (keyInfo[noteNo].keyType === Black) {
            posX += whiteKeyStep / 2.0;
          } else {
            posX += whiteKeyStep;
          }
        }
        keyInfo[noteNo].keyCenterPosX = posX;
        prevKeyType = keyInfo[noteNo].keyType;
      }
      prevKeyType = WhiteC;
      _results = [];
      for (noteNo = _j = 0; _j < 128; noteNo = ++_j) {
        if (keyInfo[noteNo].keyType === Black) {
          switch (prevKeyType) {
            case WhiteC:
              shift = -blackKeyShiftCDE;
              break;
            case WhiteD:
              shift = +blackKeyShiftCDE;
              break;
            case WhiteF:
              shift = -blackKeyShiftFGAB;
              break;
            case WhiteG:
              shift = 0.0;
              break;
            case WhiteA:
              shift = +blackKeyShiftFGAB;
              break;
            default:
              shift = 0.0;
          }
          if (noteNo === 126) {
            shift = 0.0;
          }
          keyInfo[noteNo].keyCenterPosX += shift;
        }
        _results.push(prevKeyType = keyInfo[noteNo].keyType);
      }
      return _results;
    };

    return PianoKeyboardDesign;

  })();

  PianoKey = (function() {

    PianoKey.name = 'PianoKey';

    function PianoKey(_arg) {
      var color, design, geometry, height, keyType, length, material, position, width;
      design = _arg.design, keyType = _arg.keyType, position = _arg.position;
      if (keyType === design.KeyType.Black) {
        width = design.blackKeyWidth;
        height = design.blackKeyHeight;
        length = design.blackKeyLength;
        color = design.blackKeyColor;
      } else {
        width = design.whiteKeyWidth;
        height = design.whiteKeyHeight;
        length = design.whiteKeyLength;
        color = design.whiteKeyColor;
      }
      geometry = new THREE.CubeGeometry(width, height, length);
      material = new THREE.MeshLambertMaterial({
        color: color
      });
      this.model = new THREE.Mesh(geometry, material);
      this.model.position.copy(position);
      this.keyUpSpeed = design.keyUpSpeed;
      this.originalY = position.y;
      this.pressedY = this.originalY - design.keyDip;
    }

    PianoKey.prototype.press = function() {
      this.model.position.y = this.pressedY;
      return this.isPressed = true;
    };

    PianoKey.prototype.release = function() {
      return this.isPressed = false;
    };

    PianoKey.prototype.update = function() {
      var offset;
      if (this.model.position.y < this.originalY && !this.isPressed) {
        offset = this.originalY - this.model.position.y;
        return this.model.position.y += Math.min(offset, this.keyUpSpeed);
      }
    };

    return PianoKey;

  })();

  PianoKeyboard = (function() {

    PianoKeyboard.name = 'PianoKeyboard';

    function PianoKeyboard(design) {
      this.update = __bind(this.update, this);

      var Black, blackKeyY, blackKeyZ, i, key, keyCenterPosX, keyType, keys, model, pos, _i, _len, _ref, _ref1;
      Black = design.KeyType.Black;
      model = new THREE.Object3D();
      keys = [];
      blackKeyY = (design.blackKeyHeight - design.whiteKeyHeight) / 2 + 0.001;
      blackKeyZ = (design.blackKeyLength - design.whiteKeyLength) / 2 + 0.001;
      _ref = design.keyInfo;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        _ref1 = _ref[i], keyType = _ref1.keyType, keyCenterPosX = _ref1.keyCenterPosX;
        if (keyType === Black) {
          pos = new THREE.Vector3(keyCenterPosX, blackKeyY, blackKeyZ);
        } else {
          pos = new THREE.Vector3(keyCenterPosX, 0, 0);
        }
        key = new PianoKey({
          design: design,
          keyType: keyType,
          position: pos
        });
        keys.push(key);
        if ((20 < i && i < 109)) {
          model.add(key.model);
        }
      }
      model.y -= design.whiteKeyHeight / 2;
      this.keys = keys;
      this.model = model;
    }

    PianoKeyboard.prototype.press = function(note) {
      return this.keys[note].press();
    };

    PianoKeyboard.prototype.release = function(note) {
      return this.keys[note].release();
    };

    PianoKeyboard.prototype.update = function() {
      var key, _i, _len, _ref, _results;
      _ref = this.keys;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        _results.push(key.update());
      }
      return _results;
    };

    return PianoKeyboard;

  })();

  this.PianoKeyboardDesign = PianoKeyboardDesign;

  this.PianoKeyboard = PianoKeyboard;

}).call(this);
