// Generated by CoffeeScript 1.3.1
(function() {

  $(document).ready(function() {
    window.loader = new LoaderWidget();
    window.app = new Euphony();
    app.initScene();
    return app.initMidi(function() {
      return app.getBuiltinMidiIndex(function(index) {
        return app.setBuiltinMidi(index[13], function() {
          window.player = new PlayerWidget();
          player.init();
          player.bind('play', app.play);
          player.bind('pause', app.pause);
          player.bind('resume', app.resume);
          return player.bind('stop', app.stop);
        });
      });
    });
  });

}).call(this);
