// Generated by CoffeeScript 1.3.1
(function() {

  $(document).ready(function() {
    var app;
    window.loader = new LoaderWidget();
    app = new Euphony();
    return app.start();
  });

}).call(this);
