// Generated by CoffeeScript 1.3.1
(function() {

  $(document).on('selectstart', function() {
    return false;
  }).on('ready', function() {
    window.loader = new LoaderWidget();
    window.app = new Euphony();
    app.initScene();
    return app.initMidi(function() {
      return app.getBuiltinMidiIndex(function(index) {
        window.player = new PlayerWidget('#player');
        player.setPlaylist(index);
        player.bind('pause', app.pause);
        player.bind('resume', app.resume);
        player.bind('stop', app.stop);
        player.bind('play', app.play);
        player.bind('changetrack', function(filename) {
          loader.message('Loading MIDI');
          return app.setBuiltinMidi(filename, function() {
            return loader.stop(function() {
              return player.play();
            });
          });
        });
        return player.show(function() {
          return player.changeTrack(player.getRandomTrack());
        });
      });
    });
  });

}).call(this);
