// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var design, keyboard, noteToColor, rain, scene;
    scene = new Scene('#container');
    design = new PianoKeyboardDesign();
    keyboard = new PianoKeyboard(design);
    scene.add(keyboard.model);
    scene.animate(function() {
      return keyboard.update();
    });
    rain = null;
    noteToColor = (function() {
      var map;
      map = MusicTheory.Synesthesia.map('August Aeppli (1940)');
      return function(note) {
        return parseInt(map[note - MIDI.pianoKeyOffset].hex, 16);
      };
    })();
    return MIDI.loadPlugin(function() {
      var NOTE_OFF, NOTE_ON, player, trackNames;
      player = MIDI.Player;
      NOTE_OFF = 128;
      NOTE_ON = 144;
      player.addListener(function(data) {
        var message, note;
        note = data.note, message = data.message;
        if (message === NOTE_ON) {
          return keyboard.press(note);
        } else if (message === NOTE_OFF) {
          return keyboard.release(note);
        }
      });
      trackNames = Object.keys(MIDIFiles);
      return player.loadFile(MIDIFiles[trackNames[13]], function(midifile) {
        if (rain) {
          scene.remove(rain.model);
        }
        rain = new NoteRain({
          midiData: MIDI.Player.data,
          pianoDesign: design,
          noteToColor: noteToColor
        });
        scene.add(rain.model);
        player.start();
        return player.setAnimation({
          delay: 30,
          callback: function(data) {
            return rain.update(data.now * 1000);
          }
        });
      });
    });
  });

}).call(this);
