// Generated by CoffeeScript 1.3.1
(function() {
  var Player;

  Player = (function() {

    Player.name = 'Player';

    function Player(container) {
      this.container = $(container);
    }

    return Player;

  })();

}).call(this);
